version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: radioking-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: radioking
      RABBITMQ_DEFAULT_PASS: radioking123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - radioking-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: radioking-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    command:
      - start-dev
    networks:
      - keycloak-network

  postgres:
    image: postgres:15-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
      - radioking-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  keycloak-network:
    driver: bridge
  radioking-network:
    driver: bridge